### ISSUE TITLE
Record responseTxHash

### ISSUE THREAD

**Issue by sxlwar** [helix-bridge/indexer#38]
### Substrate <> DVM

pangolin -> pangolin dvm: ✅ 
pangolin dvm -> pangolin: ❌ 
crab -> crab dvm: ✅ 
crab dvm -> crab: ❌ 

### Substrate <> Substrate DVM

pangoro -> pangolin dvm: ❌ 
pangolin dvm -> pangoro: ❌
darwinia -> crab dvm: ❌ 
crab dvm -> darwinia: ❌ 

### Substrate <> Parachain

pangolin -> pangolin parachain: ❌ 
pangolin parachain -> pangolin: ❌

**Comment by sxlwar** [comment]
Substrate <> DVM
pangolin -> pangolin dvm: ✅
pangolin dvm -> pangolin: ❌
crab -> crab dvm: ✅
crab dvm -> crab: ❌

Substrate <> Substrate DVM
pangoro -> pangolin dvm: ✅ 
pangolin dvm -> pangoro: ✅ 
darwinia -> crab dvm: ✅ 
crab dvm -> darwinia: ✅ 

Substrate <> Parachain
pangolin -> pangolin parachain: ✅ 
pangolin parachain -> pangolin: ✅

**Comment by sxlwar** [comment]
dvm -> substrate 

extract transaction_hash from **ethereum (Executed)** event

dispatch precompile:  Just listen for balance(Transfer) event

**Comment by xiaoch05** [comment]
1. Old records need to be retained
2. The new version `dvm -> substrate` can be parsed the same as `substrate -> dvm`

**Comment by sxlwar** [comment]
Substrate <> DVM
pangolin -> pangolin dvm: ✅
pangolin dvm -> pangolin: ✅ 
crab -> crab dvm: ✅
crab dvm -> crab: ✅ 

Substrate <> Substrate DVM
pangoro -> pangolin dvm: ✅
pangolin dvm -> pangoro: ✅
darwinia -> crab dvm: ✅
crab dvm -> darwinia: ✅

Substrate <> Parachain
pangolin -> pangolin parachain: ✅
pangolin parachain -> pangolin: ✅
