### ISSUE TITLE
Wrong token name

### ISSUE THREAD

**Issue by sxlwar** [helix-bridge/indexer#79]
https://github.com/helix-bridge/indexer/blob/640daa8418f382ba3b2b2c31bf5b009fca0d7252/subql/crab-parachain/src/handlers/event.ts#L122

should be CRAB

**Comment by sxlwar** [comment]
txHash:  use extrinsic id
result: 3

**Comment by xiaoch05** [comment]
https://github.com/helix-bridge/indexer/pull/80
